--- src/SDIO/driver_fw/driver/aic8800/aic8800_bsp/Makefile
+++ src/SDIO/driver_fw/driver/aic8800/aic8800_bsp/Makefile
@@ -130,6 +130,11 @@ KVER ?= $(shell uname -r)
 MODDESTDIR ?= /lib/modules/$(KVER)/kernel/drivers/net/wireless/
 ARCH ?= x86_64
 CROSS_COMPILE ?=
+
+ifeq ($(CONFIG_AW_BSP), y)
+ccflags-y += -DCONFIG_PLATFORM_ALLWINNER
+endif
+
 endif
 ###########################################
 
